; Auto-generated. Do not edit!


(cl:in-package action_learn-msg)


;//! \htmlinclude action_learnResult.msg.html

(cl:defclass <action_learnResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass action_learnResult (<action_learnResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <action_learnResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'action_learnResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_learn-msg:<action_learnResult> is deprecated: use action_learn-msg:action_learnResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <action_learnResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_learn-msg:result-val is deprecated.  Use action_learn-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <action_learnResult>) ostream)
  "Serializes a message object of type '<action_learnResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <action_learnResult>) istream)
  "Deserializes a message object of type '<action_learnResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<action_learnResult>)))
  "Returns string type for a message object of type '<action_learnResult>"
  "action_learn/action_learnResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'action_learnResult)))
  "Returns string type for a message object of type 'action_learnResult"
  "action_learn/action_learnResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<action_learnResult>)))
  "Returns md5sum for a message object of type '<action_learnResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'action_learnResult)))
  "Returns md5sum for a message object of type 'action_learnResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<action_learnResult>)))
  "Returns full string definition for message of type '<action_learnResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'action_learnResult)))
  "Returns full string definition for message of type 'action_learnResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <action_learnResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <action_learnResult>))
  "Converts a ROS message object to a list"
  (cl:list 'action_learnResult
    (cl:cons ':result (result msg))
))
