; Auto-generated. Do not edit!


(cl:in-package action_learn-msg)


;//! \htmlinclude action_learnGoal.msg.html

(cl:defclass <action_learnGoal> (roslisp-msg-protocol:ros-message)
  ((num
    :reader num
    :initarg :num
    :type cl:integer
    :initform 0))
)

(cl:defclass action_learnGoal (<action_learnGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <action_learnGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'action_learnGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_learn-msg:<action_learnGoal> is deprecated: use action_learn-msg:action_learnGoal instead.")))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <action_learnGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_learn-msg:num-val is deprecated.  Use action_learn-msg:num instead.")
  (num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <action_learnGoal>) ostream)
  "Serializes a message object of type '<action_learnGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <action_learnGoal>) istream)
  "Deserializes a message object of type '<action_learnGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<action_learnGoal>)))
  "Returns string type for a message object of type '<action_learnGoal>"
  "action_learn/action_learnGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'action_learnGoal)))
  "Returns string type for a message object of type 'action_learnGoal"
  "action_learn/action_learnGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<action_learnGoal>)))
  "Returns md5sum for a message object of type '<action_learnGoal>"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'action_learnGoal)))
  "Returns md5sum for a message object of type 'action_learnGoal"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<action_learnGoal>)))
  "Returns full string definition for message of type '<action_learnGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'action_learnGoal)))
  "Returns full string definition for message of type 'action_learnGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <action_learnGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <action_learnGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'action_learnGoal
    (cl:cons ':num (num msg))
))
