// Generated by gencpp from file action_learn/action_learnFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_LEARN_MESSAGE_ACTION_LEARNFEEDBACK_H
#define ACTION_LEARN_MESSAGE_ACTION_LEARNFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_learn
{
template <class ContainerAllocator>
struct action_learnFeedback_
{
  typedef action_learnFeedback_<ContainerAllocator> Type;

  action_learnFeedback_()
    : progress_bar(0.0)  {
    }
  action_learnFeedback_(const ContainerAllocator& _alloc)
    : progress_bar(0.0)  {
  (void)_alloc;
    }



   typedef double _progress_bar_type;
  _progress_bar_type progress_bar;





  typedef boost::shared_ptr< ::action_learn::action_learnFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_learn::action_learnFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct action_learnFeedback_

typedef ::action_learn::action_learnFeedback_<std::allocator<void> > action_learnFeedback;

typedef boost::shared_ptr< ::action_learn::action_learnFeedback > action_learnFeedbackPtr;
typedef boost::shared_ptr< ::action_learn::action_learnFeedback const> action_learnFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_learn::action_learnFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_learn::action_learnFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_learn::action_learnFeedback_<ContainerAllocator1> & lhs, const ::action_learn::action_learnFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress_bar == rhs.progress_bar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_learn::action_learnFeedback_<ContainerAllocator1> & lhs, const ::action_learn::action_learnFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_learn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_learn::action_learnFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_learn::action_learnFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_learn::action_learnFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_learn::action_learnFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_learn::action_learnFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_learn::action_learnFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_learn::action_learnFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac7532a8a8f0d2be4f5284d94fee2d59";
  }

  static const char* value(const ::action_learn::action_learnFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac7532a8a8f0d2beULL;
  static const uint64_t static_value2 = 0x4f5284d94fee2d59ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_learn::action_learnFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_learn/action_learnFeedback";
  }

  static const char* value(const ::action_learn::action_learnFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_learn::action_learnFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#连续反馈\n"
"float64 progress_bar\n"
"\n"
;
  }

  static const char* value(const ::action_learn::action_learnFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_learn::action_learnFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress_bar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct action_learnFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_learn::action_learnFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_learn::action_learnFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress_bar: ";
    Printer<double>::stream(s, indent + "  ", v.progress_bar);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_LEARN_MESSAGE_ACTION_LEARNFEEDBACK_H
